apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mytestcluster
  region: ap-south-1

nodeGroups:
  - name: small-ng
    instanceType: t2.micro
    desiredCapacity: 3

  - name: bigger-ng
    instanceType: t2.small
    desiredCapacity: 2
